apiVersion: apps/v1
kind: Deployment

metadata:
  name: worker
  namespace: ai-task-platform

spec:
  replicas: 2

  selector:
    matchLabels:
      app: worker

  template:
    metadata:
      labels:
        app: worker

    spec:
      containers:
        - name: worker

          image: bushrakhan9321/ai-task-worker:v1
          imagePullPolicy: Always

          env:
            - name: MONGO_URI
              valueFrom:
                secretKeyRef:
                  name: ai-task-platform-secrets
                  key: MONGO_URI
